name: quick-crypt-webapp
services:
  angular-build:
    build:
      context: ..
      target: build
      dockerfile: docker/Dockerfile
      args:
        BASE_HREF: /
        API_URL: '/api'
    volumes:
      - ../dist:/app/dist
      # Don't write modules back to host
      - /app/node_modules
    command: [
      '/bin/sh',
      '-c',
      'rm -rf /app/dist/*; mv /app/build/* /app/dist/'
    ]

  web-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        BASE_HREF: /
        API_URL: '/api'
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - qc-backend


networks:
  qc-backend:
    external: true
    name: quick-crypt-backend_qc_backend
